### ISSUE TITLE
Trying in test bed

### ISSUE THREAD

**Issue by harikt** [jwagner/smartcrop.js#10]
Hi @jwagner , 

Good work. I was trying on the test bed an image and it seems the cat is not detected.

Attaching image for reference. What I was trying was reducing the width and height also, the cat's face was not detected.

![cat](https://cloud.githubusercontent.com/assets/120454/10505379/5ed2cdd6-732a-11e5-8b7a-c0150d4421a0.jpeg)

**Comment by jwagner** [comment]
Hey @harikt,

Smartcrop.js does not detect faces, it detects human skin color. The cat is a bit too white for that.
The other factors are the sharpness of the image regions and their saturation. The cat is quite low in these too. That's why it is 'not detected'/not always cropped nicely.

Smartcrop.js is heuristic so it won't always work. This is one of these cases.

Still, thanks for letting me know!

**Comment by harikt** [comment]
Thank you @jwagner for the fast reply.

Thanks for the explanations also.
