### ISSUE TITLE
Blocked by SecurityError

### ISSUE THREAD

**Issue by dertin** [jwagner/smartcrop.js#30]
SecurityError: The operation is insecure.
var input = ctx.getImageData(0, 0, canvas.width, canvas.height),

**Comment by jwagner** [comment]
This is most likely because of user error. You get this error when you run SmartCrop on an image from another domain which you do not have permission to access:

image: anything ctx.drawImage() accepts, usually HTMLImageElement, HTMLCanvasElement or HTMLVideoElement. **Keep in mind that origin policies apply to the image source, and you may not use cross-domain images without CORS.**

https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
