### ISSUE TITLE
[Feature] Smart Rotate?

### ISSUE THREAD

**Issue by roblav96** [jwagner/smartcrop.js#32]
By any chance are there plans to add smart rotate? lol

I've noticed that some users are not rotating their images when uploading them.

**Comment by jwagner** [comment]
It's probably doable but:
- It's risky turning a correctly oriented image on it's head is IMO worse than selecting a bad crop.
- It probably requires a lot of machine learning/training data otherwise the woman in the sky blue dress might get turned on her head.

Do you properly handle exif orientation? That seems to be the mean cause for incorrectly rotated images in my experience.

**Comment by roblav96** [comment]
> Do you properly handle exif orientation?

I do believe so. I'm using the cordova camera plugin with
```
correctOrientation: true
```
I'm not too sure if that handles the exif properly or not.

That's pretty funny about the blue dress girl. haha

**Comment by jwagner** [comment]
If you are running inside of cordova you should definitely try to get the orientation right in there and not afterwards by invoking black magic. :)
