### ISSUE TITLE
Return just focal point

### ISSUE THREAD

**Issue by abagshaw** [jwagner/smartcrop.js#45]
Is it possible just to return a focal point (rather than getting crop info) upon which a library like https://github.com/jonom/jquery-focuspoint can then reposition an image around when used in a re-sizing window?

**Comment by jwagner** [comment]
No, this library does not produce a (focal) point, it evaluates different crops (rectangles) against the image and picks the best one.

What I have done in the past is that if there is a manually defined focal point: I'd use that one for cropping, otherwise I use smartcrop to produce a good crop. With that said I do the cropping on the servers and not on the client. It's of little use to send the entire image to the client if only a bit of it is going to be used. 

You could try to get smartcrop to find a smallish rectangle (by setting min & max scale) and then take the center of that as a center point.

IFF you really want a focal point you are probably better off using face detection (for what it's worth) and some simple edge detection + blob detection for finding a center point in other cases.

But it is, at least in my opinion, a harder problem to find a 'focal point' than to find a good crop. For the good crop you can try to include all the things that appear to be important (in focus, contrasty, faces etc.) and even arrange them in a pleasing way, for the focal point you have to pick one point and hope you got it really rong.

This answer is already to long but long story short:
Smartcrop finds good crops, not (focal) points. I think that's the better problem to solve for a computer. I think focal points are useful as a quick way & easy for humans to annotate what is important in an image. A better system is IMO to allow them to just draw an importance map (highlight the important bits with a marker) and then again let the computer find a nice crop containing those.

Cheers,
Jonas

**Comment by dbx834** [comment]
Hi,

If someone is still interested in this, an approximation can be accomplished like this, using `smartcrop-sharp`

```
smartcrop.crop(image { height: 200, width: 200 }).then((result) => {
  const crop = result.topCrop
  const cropCenterX = crop.width / 2
  const cropCenterY = crop.height / 2
  const attentionX = cropCenterX + crop.x
  const attentionY = cropCenterY + crop.y
  const attentionXPercent = ((attentionX * 100) / widthOfTheImage).toFixed(2)
  const attentionYPercent = ((attentionY * 100) / heightOfTheImage).toFixed(2)
  const attention = {
    attentionX,
    attentionY,
    attentionXPercent,
    attentionYPercent,
  }
})
```

This produces data like so:

```
{
  attentionX: 803,
  attentionY: 756,
  attentionXPercent: '42.99',
  attentionYPercent: '50.00'
}
```

As an example, in this image, `attentionX` and `attentionY` marks the red dot at the center.

<img width="572" alt="Screenshot 2025-01-07 at 10 18 46 PM" src="https://github.com/user-attachments/assets/b7629482-469c-45a7-b33b-20e8aa97b9d3" />

I have thousands of images that I need to get attention co-ordinates for, and this works fairly well for me. I am able to generate attention loci on the server.

**Comment by dbx834** [comment]
Also – my opinion is Jonas is right – that this is really a short-cut, that smartcrop is ultimately good for crops and not focus points. Perhaps machine-learning based focal point detection would be best, when that comes. Until then these are cheaper alternatives. I am happy at the moment if there are 500 incorrect or flawed focal points in my library of 5000 images! :)

Thanks for the library!

**Comment by dbx834** [comment]
> Hi,
> 
> If someone is still interested in this, an approximation can be accomplished like this, using `smartcrop-sharp`
> 
> ```
> smartcrop.crop(image { height: 200, width: 200 }).then((result) => {
>   const crop = result.topCrop
>   const cropCenterX = crop.width / 2
>   const cropCenterY = crop.height / 2
>   const attentionX = cropCenterX + crop.x
>   const attentionY = cropCenterY + crop.y
>   const attentionXPercent = ((attentionX * 100) / widthOfTheImage).toFixed(2)
>   const attentionYPercent = ((attentionY * 100) / heightOfTheImage).toFixed(2)
>   const attention = {
>     attentionX,
>     attentionY,
>     attentionXPercent,
>     attentionYPercent,
>   }
> })
> ```
> 
> This produces data like so:
> 
> ```
> {
>   attentionX: 803,
>   attentionY: 756,
>   attentionXPercent: '42.99',
>   attentionYPercent: '50.00'
> }
> ```
> 
> As an example, in this image, `attentionX` and `attentionY` marks the red dot at the center.
> <img alt="Screenshot 2025-01-07 at 10 18 46 PM" width="572" src="https://private-user-images.githubusercontent.com/4337826/400850815-b7629482-469c-45a7-b33b-20e8aa97b9d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYyNjkxMDUsIm5iZiI6MTczNjI2ODgwNSwicGF0aCI6Ii80MzM3ODI2LzQwMDg1MDgxNS1iNzYyOTQ4Mi00NjljLTQ1YTctYjMzYi0yMGU4YWE5N2I5ZDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDdUMTY1MzI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTMwYWMzMmEzZjc4YzliMGUyMDY5Mjg3MTI1MDFjNDYxOGYwM2EzNWNiOTA5YjYzNGMzOWQzZDJiMzgyODUyNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.fJOdVht5AFtEmIMuYziVg9AnPz3jk3cnf-GvGi0SnU0">
> 
> I have thousands of images that I need to get attention co-ordinates for, and this works fairly well for me. I am able to generate attention loci on the server.

Also – my opinion is Jonas is right – that this is really a short-cut, that smartcrop is ultimately good for crops and not focus points. Perhaps machine-learning based focal point detection would be best, when that comes. Until then these are cheaper alternatives. I am happy at the moment if there are 500 incorrect or flawed focal points in my library of 5000 images! :)

Thanks for the library!
