### ISSUE TITLE
Add canvas peer dependency

### ISSUE THREAD

**Issue by tolmasky** [jwagner/smartcrop.js#47]
Could you add canvas as a peer dependency (as described here: https://docs.npmjs.com/files/package.json#peerdependencies ). If you do so, then it will work on tonic (https://tonicdev.com/npm/smartcrop-node) automatically.

Thanks!

Francisco

**Comment by jwagner** [comment]
Why should I add a dependency to this module it doesn't depend on because some module built on top of it requires it?

IMO if you want to use smartcrop with node you should use either [smartcrop-sharp](https://github.com/jwagner/smartcrop-sharp) or [smartcrop-gm](https://github.com/jwagner/smartcrop-gm).
Node-canvas has been a pain to build & deploy (at least for my setups). 

Cheers,
Jonas

**Comment by tolmasky** [comment]
Hi @jwagner, I apologize, I did mean to file this on smartcrop-node and instead filed it here. Oops!
